version: "2.17.2"
services:
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: social_pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sc_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /db_data:/var/lib/postgres/data
  redis:
    image: redis:7.0.11-alpine
    container_name: social_redis
    ports:
      - 6379:6379
    volumes:
      - /db_data:/var/lib/redis/data
